### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by daltonjames777** [n0l3r/tiktok-downloader#31]
your code works quite well, is it possible to find 1 api which can download videos in hd format, similar to the api that https://musicaldown.com/en uses, to download videos in hd format?
Thank you

**Comment by timmbobb** [comment]
Hmm, I didn't even realize that it was possible to get them in a higher resolution. Wonder what would need to be done to do that here...

**Comment by jgore077** [comment]
I thought they were already pretty high in resolution

**Comment by timmbobb** [comment]
The ones downloaded using this are in 576x1024, whereas the site he mentioned above allows you to download them at 1080x1920. Would be pretty neat if we could get it to do that.

**Comment by timmbobb** [comment]
Tiktoks are also stored at 1080x1920 so it's odd that it gets a lower resolution.

**Comment by timmbobb** [comment]
The yt-dl tiktok.py (https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/tiktok.py) is capable of downloading in 1080x1920. I'm not sure I'm smart enough to figure out what they're doing differently in it to get it at 1080x1920, but it would be nice to figure out. If anyone wants to try and implement what they're doing here I would love to help.

**Comment by jgore077** [comment]
I can try to help

**Comment by jgore077** [comment]
Also I couldnt get the scraper to work without loading my own cookies

**Comment by ltm7725** [comment]
> The yt-dl tiktok.py (https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/tiktok.py) is capable of downloading in 1080x1920. I'm not sure I'm smart enough to figure out what they're doing differently in it to get it at 1080x1920, but it would be nice to figure out. If anyone wants to try and implement what they're doing here I would love to help.

I tried to dig into yt-dl a little, and was actually only able to extracting a 1080p video using OUR current API hostname (api16-normal-c-useast2a.tiktokv.com) with it instead of theirs (api22-normal-c-useast2a.tiktokv.com) which I was only receiving that 576x1024 from that we get already.

I may be missing something in the our API's return block; I'm making requests & looking through the JSON on Postman to test. But in that data I can only find direct links for a couple of the 574p formats, as opposed to ALL of these that show up using our host address on yt-dl:

![image](https://github.com/n0l3r/tiktok-downloader/assets/89643219/7141f66d-5aec-4380-b1e4-5b71226e31d4)

So I'm a bit more confused than when I started rn. If you wanna try digging into these to see if anything's sitting there you can use "https://api16-normal-c-useast2a.tiktokv.com/aweme/v1/feed/?aweme_id=[VIDEO_ID]" or "api22-normal-c-useast2a.tiktokv.com/aweme/v1/feed/?aweme_id=[VIDEO_ID]" otherwise I'll try more when I get a chance. Idk much beyond the basics when it comes to APIs themselves, but if it's not directly in the JSON block then maybe someone a little more experienced in Python than myself could look through that yt-dl code a bit more to uncover what they're extracting out of there.

**Comment by jgore077** [comment]
When you swap the endpoint with `https://api22-normal-c-useast2a.tiktokv.com/aweme/v1/feed/?aweme_id=${idVideo}` the .mp4s no longer have any content perhaps the video is some kind of bytestring? Also I had to use cookies to get my mass download to work but have you gotten it working without cookies?

**Comment by timmbobb** [comment]
I think it's the way they setup their cookies that might be why it works? Also, the way that our api downloads videos works with all tiktoks, even ones that the sound has been removed on, but if you use the yt-dlp way it will fail when it tries to download any tiktok that the sound has been removed for copyright reasons.
